name: Cyress Tests
on: deployment  
#  pull_request:
#    branches:
#    - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/vercel-cypress@v1
    - uses: actions/checkout@v2
    - uses: cypress-io/github-action@v2
      with:
        #vercel-token: ${{ secrets.VERCEL_TOKEN }}
        #build: yarn dev
        #browser: chrome
        command: yarn dev | cypress run
