name: Cyress Tests
on: deployment  
#  pull_request:
#    branches:
#    - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/vercel-cypress@v1
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        repo: learning.Cypress
