name: Cyress Tests
on: deployment  
#  pull_request:
#    branches:
#    - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/vercel-cypress@v1
    - name: Checkout
      uses: actions/checkout@v2    
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        #vercel-token: ${{ secrets.VERCEL_TOKEN }}
        #build: yarn dev
        #browser: chrome
        start: yarn dev
        #command: cypress run
